# Generated by Django 2.0.7 on 2018-08-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('ltitle', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=20000)),
                ('author', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('pageViews', models.IntegerField(max_length=20)),
                ('favorite', models.IntegerField(max_length=20)),
            ],
        ),
    ]
